### ISSUE TITLE
The correct direction to integrate a h5p library

### ISSUE THREAD

**Issue by Hungpv-ashen** [EscolaSoft/Laravel-H5P#1]
Hello.

I am trying to integrate h5p libraries in my project using your package.

I have followed the steps as instructed on the readme and here are my results.

![image](https://user-images.githubusercontent.com/61173700/104176619-21fd0b00-543a-11eb-953c-c89b93d6c700.png)

However, when you press save, it all shows an error page: Maximum function nesting level of '256' reached, aborting !.

I searched on google a few ways to get around this error, but it doesn't seem to work for me. So what did I do wrong and where is the exact guide for this.

I use laravel framework 7.29 on wampp server php 7.3.5, apache 2.4.39 and mysql 5.7.26.

Thank you very much.

**Comment by qunabu** [comment]
I'm working on the demo https://github.com/EscolaSoft/Laravel-H5P-demo

**Comment by Hungpv-ashen** [comment]
Thank you so much for guiding me. I will try it.

**Comment by Hungpv-ashen** [comment]
Hello.

I tried your demo at https://github.com/EscolaSoft/Laravel-H5P-demo. It is good.

However, when I tried to integrate again with the instructions on README.md https://github.com/EscolaSoft/Laravel-H5P, it only worked with uploading h5p file.

![image](https://user-images.githubusercontent.com/61173700/105285447-01c20e80-5be7-11eb-802e-0fa96753e661.png)

But creating h5p-based content on every upload, it seems to be getting the error that the exact route cannot be found.

![image](https://user-images.githubusercontent.com/61173700/105285580-42218c80-5be7-11eb-8428-b7cba2566a0a.png)

This is the url being used:
http://www.studio.local/admin/h5p/ajax/7849051c/content-type-cache
But if access to url: 
http://www.studio.local/admin/h5p/ajax/content-type-cache
![image](https://user-images.githubusercontent.com/61173700/105285937-f1f6fa00-5be7-11eb-9005-90a4b3441446.png)

So what did I miss?

Thank you very much.

**Comment by qunabu** [comment]
I'm going to check this, yet please do not expect a quick answer, most likely beginning of next week.

**Comment by Hungpv-ashen** [comment]
I have found the answer to this problem.

It looks like the ajax function loads the library in the file ... \ h5p-editor \ scripts \ h5peditor-editor.js line 172 uses a variable h5p_hub_is_enabled of the config file to change the link.

![image](https://user-images.githubusercontent.com/61173700/105327523-8cb00280-5c01-11eb-9903-7fd51bd41346.png)

All you need to do is change the value of the variable "h5p_hub_is_enabled" in the config / laravel-h5p.php file from true to false.
Ps: Run: 
`php artisan config: cache.`
Thanks for your help
