### ISSUE TITLE
Cannot create H5P Content

### ISSUE THREAD

**Issue by YashGovekar** [EscolaSoft/Laravel-H5P#5]
![image](https://user-images.githubusercontent.com/18413559/108473975-bcabfd80-72b4-11eb-81c9-3ba11f5d555d.png)

I don't know if I am doing something wrong. Please if someone can guide me through this?

This URL is : /admin/h5p/h5p/create

**Comment by qunabu** [comment]
I'll get into it some day

**Comment by YashGovekar** [comment]
> I'll get into it some day

Thanks! :)

**Comment by qunabu** [comment]
https://github.com/EscolaSoft/Laravel-H5P-demo have you checked the demo before 

You need to add at least 1 library before you can add content - have you done it ?

**Comment by YashGovekar** [comment]
Okay figured it out. Thanks!
Now I have one more problem. How do I enable score check for particular content? 
Trying to figure it out..

**Comment by qunabu** [comment]
you need to listen for xAPI events, see h5p documentation

**Comment by qunabu** [comment]
https://h5p.org/documentation/for-authors/analyzing-results-and-answers 

in `blade` template (eg https://github.com/EscolaSoft/Laravel-H5P/blob/main/views/h5p/content/embed.blade.php)  you need to listen for events 

```js
        H5P.externalDispatcher.on('xAPI', function (event) {
          console.log(event.data)
        });
```

then parse is

**Comment by YashGovekar** [comment]
Oh great, working. Thankyou once again for your efforts.
Really appreciated !
